[package]
name = "wcrs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.10", features = ["derive"] }
assert_cmd = "2"
predicates = "3.0.4"
rand = "0.8"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "^3.0"
