name: Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run tests on the project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3.0.0
      
      - name: Install Rust
        run: |
          rustup update --no-self-update
      
      - name: Run tests
        run: |
          cargo test